// Generated by CoffeeScript 1.7.1
import x from './resources/default';

import C from './resources/default-class';

describe('test import default', function() {
  return it('equals 42', function() {
    expect(x).toBe(42);
    expect(new C().m()).toBe('m');
  });
});
